[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = { command = "prettier", args = ["--stdin-filepath", "file.ts"] }

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = { command = "prettier", args = ["--stdin-filepath", "file.js"] }


[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]