# Transparent background theme for Helix

# === UI ===
"ui.background" = "none"
"ui.text" = "white"

"ui.cursor.insert" = "light-yellow"
"ui.selection" = { bg = "gray", fg = "black" }

"ui.linenr" = "gray"
"ui.linenr.selected" = "white"

"ui.statusline" = "blue"
"ui.statusline.normal" = "light-blue"
"ui.statusline.insert" = "green"
"ui.statusline.select" = "cyan"
"ui.cursorline" = "gray"

"ui.popup" = { bg = "black", fg = "white" }
"ui.menu" = { bg = "black", fg = "light-blue" }

"ui.virtual" = "gray"
"ui.help" = "light-magenta"
"ui.gutter" = "gray"
"ui.debug.breakpoint" = "red"
"ui.error" = { fg = "red", underline = { style = "line", color = "red" } }

# === Optional syntax for inlay hints ===
"inlay-hint" = { fg = "gray", modifiers = ["italic"] }

# === Diagnostic underlines (from LSP) ===
"diagnostic.error" = { underline = { style = "line", color = "red" } }
"diagnostic.warning" = { underline = { style = "line", color = "yellow" } }
"diagnostic.info" = { underline = { style = "line", color = "blue" } }
"diagnostic.hint" = { underline = { style = "line", color = "gray" } }

# === Syntax Highlights (just a few examples, add more if needed) ===
"keyword" = { fg = "light-magenta", modifiers = ["bold"] }
"function" = { fg = "light-green", modifiers = ["italic"] }
"string" = { fg = "yellow" }
"comment" = { fg = "gray", modifiers = ["italic"] }

"variable" = { fg = "light-blue" }
"variable.parameter" = { fg = "light-green" }
"variable.builtin" = { fg = "cyan" }
